fix: added support for the genesis sub-command
Allows binaries built with Cosmos SDK 0.47+ to start

---------

Co-authored-by: Greg Szabo <16846635+greg-szabo@users.noreply.github.com>

diff --git a/bin/lib-gm b/bin/lib-gm
--- a/bin/lib-gm
+++ b/bin/lib-gm
@@ -262,6 +262,12 @@ enforce_requirements() {
   if [ $((MAJOR)) -eq 0 ] && [ $((MINOR)) -lt 7 ]; then
     exit_with_error "stoml too old, install 0.7.0 or newer from https://github.com/freshautomations/stoml/releases"
   fi
+  if [ -z "$(which sort || echo)" ]; then
+    exit_with_error "missing sort, please install it"
+  fi
+  if ! test "$(echo "a\nb" | sort -Vr | sed -n '1p')" = "b"; then
+    exit_with_error "missing sort -V, please install a newer version of sort"
+  fi
 }
 
 is_json_output() {
@@ -500,6 +506,31 @@ get_chain_id() {
   fi
 }
 
+# Returns empty string if --long is not supported
+get_sdk_version() {
+  GAIAD_BINARY="$(get_gaiad_binary "$1")"
+  RESULT="$("$GAIAD_BINARY" version --long 2>&1 | sed -n '/cosmos_sdk_version/ s/cosmos_sdk_version: v\(.*\)$/\1/p')"
+  echo "$RESULT"
+}
+
+get_genesis_cmd_prefix() {
+    GENESIS_BREAKING_VERSION="0.47.0"
+    SDK_VERSION="$(get_sdk_version "$1")"
+    RESULT=""
+    if [ -z "$SDK_VERSION" ]; then
+      # Handle the sdk version error here, happens when --long is not supported
+      GAIAD_BINARY="$(get_gaiad_binary "$1")"
+      RESULT="$($GAIAD_BINARY | grep -q 'gentx' || echo "genesis")"
+    else
+      HIGHER_VERSION=$(echo "${GENESIS_BREAKING_VERSION}\n${SDK_VERSION}" | sort -Vr | sed -n '1p')
+      if [ "$HIGHER_VERSION" = "$SDK_VERSION" ]; then
+        # Perform actions for the >= 0.47.0 case here
+        RESULT="genesis"
+      fi
+    fi
+    echo "$RESULT"
+}
+
 get_add_to_hermes() {
   RESULT="$(stoml -q "$CONFIG_FILE" "${1}.add_to_hermes")"
   if [ -z "$RESULT" ]; then
@@ -630,21 +661,28 @@ create() {
       EXTRA_WALLETS_COUNTER="$((EXTRA_WALLETS_COUNTER - 1))"
     done
     # Add accounts to genesis
+    GENESIS_CMD_PREFIX=$(get_genesis_cmd_prefix "$1")
     DENOM="$(get_staking_denom "$1")"
-    "$GAIAD_BINARY" add-genesis-account validator "100000000${DENOM},100000000samoleans" --keyring-backend test --home "${HOME_DIR}"
-    "$GAIAD_BINARY" add-genesis-account wallet "100000000${DENOM},100000000samoleans" --keyring-backend test --home "${HOME_DIR}"
+    # shellcheck disable=SC2086
+    "$GAIAD_BINARY" $GENESIS_CMD_PREFIX add-genesis-account validator "100000000${DENOM},100000000samoleans" --keyring-backend test --home "${HOME_DIR}"
+    # shellcheck disable=SC2086
+    "$GAIAD_BINARY" $GENESIS_CMD_PREFIX add-genesis-account wallet "100000000${DENOM},100000000samoleans" --keyring-backend test --home "${HOME_DIR}"
     EXTRA_WALLETS_COUNTER="$(get_extra_wallets "$1")"
     while [ "$EXTRA_WALLETS_COUNTER" -gt 0 ];
     do
-      "$GAIAD_BINARY" add-genesis-account "wallet${EXTRA_WALLETS_COUNTER}" "100000000${DENOM},100000000samoleans" --keyring-backend test --home "${HOME_DIR}"
+      # shellcheck disable=SC2086
+      "$GAIAD_BINARY" $GENESIS_CMD_PREFIX add-genesis-account "wallet${EXTRA_WALLETS_COUNTER}" "100000000${DENOM},100000000samoleans" --keyring-backend test --home "${HOME_DIR}"
       EXTRA_WALLETS_COUNTER="$((EXTRA_WALLETS_COUNTER - 1))"
     done
     # Create gentx
-    "$GAIAD_BINARY" gentx validator "1000000${DENOM}" --keyring-backend test --keyring-dir "${HOME_DIR}" --home "${HOME_DIR}" --chain-id "$1" 2> /dev/null
+    # shellcheck disable=SC2086
+    "$GAIAD_BINARY" $GENESIS_CMD_PREFIX gentx validator "1000000${DENOM}" --keyring-backend test --keyring-dir "${HOME_DIR}" --home "${HOME_DIR}" --chain-id "$1" 2> /dev/null
     # Collect gentxs
-    "$GAIAD_BINARY" collect-gentxs --home "${HOME_DIR}" 2> /dev/null
+    # shellcheck disable=SC2086
+    "$GAIAD_BINARY" $GENESIS_CMD_PREFIX collect-gentxs --home "${HOME_DIR}" 2> /dev/null
     # Validate genesis
-    "$GAIAD_BINARY" validate-genesis --home "${HOME_DIR}" > /dev/null
+    # shellcheck disable=SC2086
+    "$GAIAD_BINARY" $GENESIS_CMD_PREFIX validate-genesis --home "${HOME_DIR}" > /dev/null
   else
     NETWORK_HOME_DIR="$(get_home_dir "$NETWORK")"
     if [ -f "$NETWORK_HOME_DIR/config/genesis.json" ]; then
@@ -723,10 +761,12 @@ start() {
   if is_running "$1"; then
     warn "$1 is already running, skipping"
   else
+    [ -z ${GENESIS_CMD_PREFIX+x} ] && GENESIS_CMD_PREFIX=$(get_genesis_cmd_prefix "$1")
     GAIAD_BINARY="$(get_gaiad_binary "$1")"
     HOME_DIR="$(get_home_dir "$1")"
     GAIAD_LOG="${HOME_DIR}/log"
-    VALIDATION="$("$GAIAD_BINARY" validate-genesis --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 || echo "ERR")"
+    # shellcheck disable=SC2086
+    VALIDATION="$("$GAIAD_BINARY" $GENESIS_CMD_PREFIX validate-genesis --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 || echo "ERR")"
     if [ "$VALIDATION" = "ERR" ]; then
       warn "validate-genesis could not complete for ${1}"
     fi
